# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnId', models.CharField(max_length=250)),
                ('RTimeStamp', models.CharField(max_length=100)),
                ('ReturnReason', models.CharField(max_length=500)),
                ('ReturnFeedback', models.CharField(max_length=500)),
                ('ProdOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product')),
            ],
        ),
    ]
