# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_returnorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnOrder',
            new_name='return_order',
        ),
    ]
