# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170415_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_order',
            name='ProductId',
        ),
    ]
