# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_return_order_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='Prourl',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
