# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productorder_prourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='Prourl',
        ),
        migrations.AddField(
            model_name='product',
            name='Prourl',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
