# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_return_order_productquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_order',
            name='ProductQuality',
            field=models.CharField(choices=[('Excellent - Unopened', 'Excellent - Unopened'), ('Good - Slightly Used', 'Good - Slightly Used'), ('Poor - Broken', 'Poor - Broken')], max_length=500),
        ),
    ]
