# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170422_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_order',
            name='ReturnReason',
            field=models.CharField(choices=[('Product Damaged', 'Product Damaged'), ('Item arrived too late', 'Item arrived too late'), ('Missing Parts or accesories', 'Missing Parts or accesories'), ('Product and shipping box both damaged', 'Product and shipping box both damaged'), ('Wrong item sent', 'Wrong item sent'), ('Item defective', 'Item defective'), ('Item no longer needed', 'Item no longer needed')], max_length=500),
        ),
    ]
