# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20170422_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_order',
            name='id',
        ),
        migrations.AlterField(
            model_name='return_order',
            name='ReturnId',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
