# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20170422_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_order',
            name='ProductName',
        ),
        migrations.AddField(
            model_name='return_order',
            name='ProductId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Product'),
            preserve_default=False,
        ),
    ]
