# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_auto_20170422_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProBuyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
